
SELECT AVG(SALARY)
FROM 
(SELECT SALARY FROM EMPLOYEES
ORDER BY SALARY
LIMIT 5
) AS SALARYTABLE;

SELECT *
FROM EMPLOYEES
WHERE YEAR(FROM_DAYS(
	DATEDIFF(CURRENT_DATE,B_DATE))) > 
    (SELECT AVG(YEAR(FROM_DAYS(DATEDIFF(CURRENT_DATE,B_DATE)))) 
    FROM EMPLOYEES);

SELECT 
	EMPL_ID, 
	JOBS_ID,
	DEPT_ID,
	YEAR(FROM_DAYS(DATEDIFF(CURRENT_DATE, START_DATE))) AS YEARS_OF_SERVICE,
	(SELECT AVG(YEAR(FROM_DAYS(DATEDIFF(CURRENT_DATE, START_DATE))))
	FROM JOB_HISTORY) AS AVG_YEARS_OF_SERVICE
	FROM JOB_HISTORY;
	

