SELECT AVG(COST/QUANTITY) FROM PETRESCUE WHERE ANIMAL = 'Dog';

SELECT DISTINCT UCASE(ANIMAL) FROM PETRESCUE;

SELECT * FROM PETRESCUE WHERE LCASE(ANIMAL) = 'cat';

SELECT SUM(QUANTITY) FROM PETRESCUE WHERE MONTH(RESCUEDATE) = 5;
/*--SELECT SUM(QUANTITY) FROM PETRESCUE WHERE MONTH(RESCUEDATE)="05";  --also works*/

SELECT ID,  RESCUEDATE, DATE_ADD(RESCUEDATE, INTERVAL 1 YEAR) AS TARGETDATE
FROM PETRESCUE;
