SELECT F_NAME, L_NAME FROM EMPLOYEES WHERE ADDRESS LIKE '%Elgin,IL%';

SELECT F_NAME, L_NAME FROM EMPLOYEES WHERE B_DATE LIKE '197%';

SELECT * FROM EMPLOYEES WHERE (SALARY BETWEEN 60000 AND 70000) AND DEP_ID = 5;
